version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "rust"
    reviewers:
      - "applone"
    assignees:
      - "applone"
    commit-message:
      prefix: "chore(deps)"
    groups:
      cargo-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "applone"
    assignees:
      - "applone"
    commit-message:
      prefix: "chore(deps)"
    groups:
      pip-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    reviewers:
      - "applone"
    assignees:
      - "applone"
    commit-message:
      prefix: "ci(deps)"
